//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class enroll
    {
        public int Sno { get; set; }
        public Nullable<int> Skill_Id { get; set; }
        public Nullable<int> Session_Id { get; set; }
        public Nullable<int> User_Id { get; set; }
    
        public virtual session_Details session_Details { get; set; }
        public virtual skillset skillset { get; set; }
        public virtual userreg userreg { get; set; }
    }
}
