//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMC2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AMCEntities1 : DbContext
    {
        public AMCEntities1()
            : base("name=AMCEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<adminreg> adminregs { get; set; }
        public virtual DbSet<enroll> enrolls { get; set; }
        public virtual DbSet<Feedback> Feedbacks { get; set; }
        public virtual DbSet<session_Details> session_Details { get; set; }
        public virtual DbSet<skillset> skillsets { get; set; }
        public virtual DbSet<trainerreg> trainerregs { get; set; }
        public virtual DbSet<userreg> userregs { get; set; }
    }
}
