//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class trainerreg
    {
        public bool selection_Id { get; set; }
        public int Trainer_Id { get; set; }
        public string Trainer_Name { get; set; }
        public string Contact_Number { get; set; }
        public string Email { get; set; }
        public Nullable<int> Skill_Id { get; set; }
        public Nullable<int> Session_Id { get; set; }
    
        public virtual session_Details session_Details { get; set; }
        public virtual skillset skillset { get; set; }
    }
}
