//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class userreg
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int Emp_Id { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
    }
}
